# 自定义配置
custom:
  info:
    version: 1.0
  # knife4j doc.html 账号/密码
  knife4j:
    username: knife4j
    password: knife4j

server:
  port: 8100

spring:
  web:
    resources:
      add-mappings: false
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

# knife4j 配置
knife4j:
  enable: true
  basic:
    enable: true
    username: ${custom.knife4j.username}
    password: ${custom.knife4j.password}
  setting:
    language: zh_cn
    enable-home-custom: true
    home-custom-path: classpath:doc/home.md

